#!/bin/bash
# launch prolog with the built library
source buildenv.sh
valgrind --tool=callgrind --dump-instr=yes --collect-jumps=yes swipl -g "asserta(file_search_path(foreign,'$PWD/$PACKSODIR'))" -g "['./prolog/terminus_store.pl']" -g version "$@"
