extern PL_blob_t store_blob_type;
extern PL_blob_t database_blob_type;
extern PL_blob_t layer_blob_type;
extern PL_blob_t layer_builder_blob_type;
extern PL_blob_t subject_lookup_blob_type;
extern PL_blob_t subject_predicate_lookup_blob_type;
extern PL_blob_t object_lookup_blob_type;
